### ISSUE TITLE
Death upon teleporting

### ISSUE THREAD

**Issue by JadeDrgn** [davqvist/Exoria#208] opened 2018-05-20 06:57 UTC
Whenever I teleport using a waystone while standing on ash (the ash that the world is made of), and the destination point is a full solid block, I die from "falling from a high place", or at least that's what the death message says anyway.

**Comment by thaimichael** [comment] 2018-05-20 11:32
I was getting ready to post this but since JadeDrgn has I will add a few comments.  This has occurred with the new update using waystones that never caused injury now causes instant death i.e. the waystone at my roots house which was never moved.  Also walking around causes random injury which at first attributed to possible latency but have come to the conclusion I am not the only one experiencing this  and it is occurring even when descending even one block level.  Gateways i.e. misty world does not seem to be affected by this.

**Comment by redcatone** [comment] 2018-05-20 13:37
Looks like it's caused by [VanillaFix](https://github.com/DimensionalDevelopment/VanillaFix/issues/29). Already fixed so just a matter of updating the mod once it releases on curseforge.

**Comment by davqvist** [comment] 2018-05-30 17:33
Yes, this was fixed in 1.0.2

**Closed as completed by davqvist** 2018-05-30 17:33 UTC
