### ISSUE TITLE
Can't create sieve, even when recipe is unlocked.

### ISSUE THREAD

**Issue by TachiOni** [davqvist/Exoria#286] opened 2018-06-12 12:02 UTC

**Comment by McRayJason** [comment] 2018-06-12 12:33
You need to use Crafting Station to craft a sieve. Vanilla Immersive Craft crafting table doesn't work with unlocked recipes.

**Comment by davqvist** [comment] 2018-06-12 20:08
Known issue, duplicate of https://github.com/davqvist/Exoria/issues/200

**Closed as completed by davqvist** 2018-06-12 20:08 UTC
Labels: duplicate
