### ISSUE TITLE
I can`t craft sieve after unlocking "Sieving_knowledge".

### ISSUE THREAD

**Issue by UMTTEPATOP** [davqvist/Exoria#296] opened 2018-06-16 01:44 UTC
When i got Sieving knowledge i ran to my crafting table to make this sieve, and when i put all the items, i could not take the sieve, because it wasn`t showing after the "->" button. I tried to add craft to crafting table with "?" then + (when items automatically stands on crafting table if u have it when chosen item). And it appeared, but i anyway couldn`t take it. I checked the craft, pressed exit and returned in the world, closed minecraft completely and launched it again. Nothing helped. And the single way i wound to get this sieve, is throwing all items for sieve in lava and using button "Open to lan" get cheats on, go into /gm 1 and take this sieve. Thank you for attention.

**Comment by ZeroLyfe** [comment] 2018-06-16 02:14
you need to do the grinding my gears quest on the survival tab then the making things easier quest on the resource automation page to unlock the ability to make the tinkers crafting station. Some of the early recipes will not craft on the beginner table and need the tinkers station to be craftable.

**Comment by davqvist** [comment] 2018-06-16 08:22
This is a known bug, so do what ZeroLyfe said and this is basically a duplicate of https://github.com/davqvist/Exoria/issues/200 so I am closing this now

**Closed as completed by davqvist** 2018-06-16 08:22 UTC
Labels: duplicate
