### ISSUE TITLE
Dimensional Control New Dim Load Crash

### ISSUE THREAD

**Issue by ChosenArchitect** [davqvist/Exoria#174] opened 2018-05-11 23:12 UTC
When loading both the underground and core dimension for the first time in single player its freezes the game and keeps saying waiting for sever and when you try to log out of your world it crashed the client.

**Comment by davqvist** [comment] 2018-05-12 10:28
I assume this a duplicate of your own issue https://github.com/davqvist/Exoria/issues/167

Please read the Important Notes when you start the pack. Number 2 tells you that you expect lag when creating a dimension, don't attempt to log out, just wait.

And without a crash log, there is nothing I can do

**Comment by davqvist** [comment] 2018-05-13 03:33
Closing this now, if you have a crash log, add it to #167

**Closed as completed by davqvist** 2018-05-13 03:33 UTC
Labels: duplicate, help wanted
