### ISSUE TITLE
Compact machines causing crash to title

### ISSUE THREAD

**Issue by orynstarheart** [davqvist/Exoria#273] opened 2018-06-07 06:28 UTC
[crash-2018-06-06_20.58.32-server.txt](https://github.com/davqvist/Exoria/files/2079171/crash-2018-06-06_20.58.32-server.txt)

**Comment by orynstarheart** [comment] 2018-06-07 06:29
caused when entering any of the machines

**Comment by davqvist** [comment] 2018-06-07 06:38
Duplicate of https://github.com/davqvist/Exoria/issues/201

**Closed as completed by davqvist** 2018-06-07 06:38 UTC
Labels: duplicate
