### ISSUE TITLE
Can't Make Burnium 

### ISSUE THREAD

**Issue by ChosenArchitect** [davqvist/Exoria#172] opened 2018-05-11 02:51 UTC
The process gets stuck at 100% and never makes that ticking sound. It seems to be getting stuck for some reason. Everything else seems to work. 
![2018-05-10_21 49 57](https://user-images.githubusercontent.com/35053440/39904197-5945e460-549c-11e8-8acf-ed3aa51fe219.png)

**Comment by davqvist** [comment] 2018-05-11 02:57
Uhm, that seems weird. No one had this issue before. Is maybe the chest below full or something?

**Comment by ChosenArchitect** [comment] 2018-05-11 05:16
ill check the hopper but it would work unless the tag for burnium dust and burnium are the same and the filtered hopper won't let them the burnium itself in... if that's the case then ill try just a chest under and hopefully that will fix it.

**Comment by thaimichael** [comment] 2018-05-11 08:17
I just use a chest below and no issues

**Comment by ChosenArchitect** [comment] 2018-05-11 17:44
Yep will do

**Comment by davqvist** [comment] 2018-05-13 03:21
Closing this, can't replicate, feel free to describe it better for me to replicate, then I will open it again

**Comment by NerdySpider** [comment] 2018-05-19 16:25
@davqvist 

I can confirm this is a issue.
Using a filtered hopper set to burnium dust as a blacklist, and the condenser at 100% for making burnium causes it to be stuck at the 100% level until the burnium dust is removed from the filter. 

I think this might be caused from the items both having the same ID but a different number. the dust form being Terraqueous:item_main with a number of 251, while the crystal form has a ID of 50.  so it might be the names clashing with the filtered hopper and the condenser

**Comment by davqvist** [comment] 2018-05-19 16:36
Might be an issue with the filtered hopper then, maybe? I will look into it, but why are you using a Filtered hopper anyway, just put a chest, box or crate below.

**Comment by 630R63** [comment] 2018-05-20 03:28
I think the reason they are using a filtered hopper is due to a bug with Sky Resources' Condenser. After placing it in the world and re-logging (others report that even going to the nether and coming back triggers this), the condenser will output it's content (in this case, the burnium dust) into the hopper below. The only solution I found is to break the condenser and place it back down every time you log in into the world.

https://github.com/Bartz24/SkyResources/issues/129

**Comment by PrincessOfEvil** [comment] 2018-05-20 08:22
I don't think it's a bug, actually. The Condenser simply doesn't try to output if it cannot do that to the block below, so the items aren't wasted if the chest is full, for instance. It's there in the ingame SR guide.

EDIT: Can't see why it exposes its input slot to automation, though.

**Comment by NerdySpider** [comment] 2018-05-21 03:29
@laz2727 

This is though, If you set the hopper to stop it from pulling another item from the input such as pulverised coal or diamond dust. It still works. Its just burnium that seems to break it.

**Comment by davqvist** [comment] 2018-05-30 17:38
I will close this. There is no reason to use a hopper in the first place even if there is a bug.

**Closed as completed by davqvist** 2018-05-30 17:38 UTC
Labels: can't replicate
