### ISSUE TITLE
[WayStone] Fell from the high place?

### ISSUE THREAD

**Issue by hron84** [davqvist/Exoria#223] opened 2018-05-22 17:16 UTC
I ran into a strange issue. Previously I stole some Waystones from looted structures (such as Altar, Runic Circle, etc) and used one to teleport between the "Home Portal" and my actual basement (I choose to not expand a platform on a hill but instead make a buried base). After the latest update, I always die if I teleport into a closed room at Y level 63 , and I got hurt to one heart when I teleport to an open space at Y 83. I think this should not work on this way.

**Comment by redcatone** [comment] 2018-05-22 17:22
Duplicate of https://github.com/davqvist/Exoria/issues/208.
Might be fixed by 1.0.2 of the pack with the update to VanillaFix, but I haven't tested it myself

**Comment by hron84** [comment] 2018-05-22 17:29
@redcatone can I safely disable vanillafix?

**Comment by redcatone** [comment] 2018-05-22 17:31
Yeah it doesn't affect progression in any way. It's a general performance/utility mod akin to FoamFix and the like.

**Comment by hron84** [comment] 2018-05-22 17:33
@redcatone ok, I'm not the stage to get into new dimension or other place than Exoria, so I think i disable it until the next update. Thanks for the great assistance anyway!

**Comment by davqvist** [comment] 2018-05-30 17:30
Definitely fixed in 1.0.2

**Closed as completed by davqvist** 2018-05-30 17:30 UTC

**Comment by hron84** [comment] 2018-05-31 00:32
Confirmed.
