### ISSUE TITLE
Shift Click Crash | Chisel and Bits in JEI

### ISSUE THREAD

**Issue by ChosenArchitect** [davqvist/Exoria#173] opened 2018-05-11 22:28 UTC
Can repeat if I search the word *craft* in jei then shift-click an item in my inventory it will crash. Crash log https://pastebin.com/vatQz9iH I believe it is Chisel and Bits related

**Comment by Rasip** [comment] 2018-05-15 06:13
Also having frequent crashes with shift clicking. Crashes even with nothing in the JEI search. https://pastebin.com/ssn1uJ2g

Removing chisels and bits removed the problem.

**Comment by davqvist** [comment] 2018-05-15 15:18
Another crash log that might be the same issue: https://pastebin.com/sYZ38kji

**Comment by Artemah** [comment] 2018-05-15 16:58
I think this is related too: https://pastebin.com/0SHsP6Pa

**Comment by TheGuy20** [comment] 2018-05-16 03:50
Typing "craft" and holding shift and pressing 2 to attempt to make an @ symbol also causes the crash.

**Comment by PaulMurrayCbr** [comment] 2018-05-17 07:52
Me too: https://pastebin.com/PGk5Z6MF

Got this when converting a stack of ash to ash blocks. Also got it after removing the block behind a storage shelf, but I'm not sure if that is related. The world can't be reloaded, which is a bit of a bummer.

The bug report in the mod that the offending class ru.liahim.mist.init.BlockColoring seems to belong to is here: https://github.com/Liahim85/MistyWorld/issues/41

**Comment by SephirothWS** [comment] 2018-05-17 16:56
I only started getting this crash after I crafted some vanilla stone tools and started using them.

https://pastebin.com/bsQKGHEu
https://pastebin.com/qf4yEBQQ

**Comment by Hugna** [comment] 2018-05-18 20:13
After having to reload several times, it is the Chisel Bit Bag causing a crash whenever touching the shift button is used.

The reproduction is simple. Go to any GUI with the JEI bar on it, type in search "chisel bit bag", and the second you push shift while that bit bag is displayed on-screen, a crash occurs. Not a shift-click, but just any interaction with the shift key.

If it doesn't break the mod pack, it'd be easily suggested to disable it until a fix is in order. Don't know what is destroying the game this way. Whatever is causing interaction with the chisel bit bag via shift (and i don't mean hovering over it, i mean pressing shift with the mouse ANYWHERE), may need to be fixed by the mod creator, or whatever merged the mods together.

**Comment by Bixxith** [comment] 2018-05-19 05:30
Since updating to the newest version I've had 4 crashes in under 20 minutes.  Shift clicking insert into a chest twice, shift clicking a recipe, and it crashed once after just pressing shift before I could even click.

**Comment by davqvist** [comment] 2018-05-19 06:53
Search for something different in JEI or disable Chisel & Bits temporarily. Not a lot more I can do.

**Comment by TheGuy20** [comment] 2018-05-20 00:48
Here's a temporary fix you can do in the meantime.

- Click the wrench in JEI to enter config
- Turn on hide mode and exit the config menu
- Type @bits in the JEI search field
- Hold CTRL and click all of the items
- Go back to JEI config and turn off hide mode

**Comment by AlgorithmX2** [comment] 2018-05-20 19:16
Since there hasn't been any movement on the MistyWorld side of the issue, I thought I would throw a quick test in to avoid sending air though its method which is causing the crash.

https://www.dropbox.com/s/50li6e7aoztvdia/chiselsandbits-14.17.jar?dl=1 if someone wants to confirm that this bypasses the issue.

**Comment by TheGuy20** [comment] 2018-05-21 03:01
I couldn't get it to crash after the fix. Great job

**Closed as completed** 2018-05-30 17:39 UTC
Labels: bug, reported to dev, critical
