### ISSUE TITLE
No way to get primalcore lit torch for 'fire me up' quest

### ISSUE THREAD

**Issue by ChiefLogan3010** [davqvist/Exoria#14] opened 2017-10-08 15:20 UTC
When you sneak-right click as the tooltip on the un-lit torch says, it gives you a vanilla torch which then disappears when trying to place it.

**Comment by davqvist** [comment] 2017-10-08 15:22
Sneak right click on the lit torch right?

**Comment by ChiefLogan3010** [comment] 2017-10-08 15:51
Yep, when I do that it gives a vanilla torch rather than a primal lit torch.

**Comment by DJJBanx** [comment] 2017-10-08 16:49
It does work.

**Comment by davqvist** [comment] 2017-10-09 04:49
Right click with unlit torch on lit torch to light them.
Still weird that you get a vanilla one.
I will investigate

**Comment by weedgoku** [comment] 2018-05-16 00:43
This issue is still not fixed.

**Comment by davqvist** [comment] 2018-05-16 00:50
I know, that is why the issue is still open. Do what I wrote above though

**Comment by davqvist** [comment] 2018-07-18 09:59
Will be fixed in 1.3.0

**Closed as completed by davqvist** 2018-07-18 09:59 UTC
Labels: reported to dev, Minor
