### ISSUE TITLE
Crafting Recipe Conflict

### ISSUE THREAD

**Issue by Draconess** [davqvist/Exoria#205] opened 2018-05-20 02:10 UTC
The recipe for the dense net using string is the same as the recipe for crafting cobweb using string.  when using the preset craft dense net it only will craft cobweb.

**Comment by redcatone** [comment] 2018-05-20 02:34
Duplicate of https://github.com/davqvist/Exoria/issues/192 and was fixed in 1.0.1

**Closed as completed** 2018-05-20 03:59 UTC
